# ??????
server:
  # ????HTTP??????8080
  servlet:
    # ???????
    context-path: /auth-serve
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # ?????????????100
    accept-count: 1000
    threads:
      # tomcat?????????200
      max: 800
      # Tomcat?????????????10
      min-spare: 100
  port: 11000


cloud-voice-config-properties:
  appkey: bvrugwyhl2p2j32bs7o4dm6t5yh3uktddjzaqhyf
  appSecret: 69c7e254e9582c1f1fb0e7190923e6c5
  groupId: 4d677852-84ef-4350-8fcf-5ce2542eb8ed

keda-config-properties:
  requestUrl: https://api.xf-yun.com/v1/private/s782b4996
  APPID: 0d37f0e6
  APISecret: MDVlMjdhZmVhZjBjMjk5OGU4YTQwZjAy
  APIKey: 1e0c53e352b81097272a9816cf5cdd05
  groupId: 20231201KD_VOICE_GROUP_ID

baidu-config-properties:
  apiKey: gLsGjmbLEr1frbWyKHcyyRGp
  secretKey: 1GwcBaoQfybgEHVoOv52LGssxNuffqyb


upload-config:
  path: /www/wwwroot/fvAuth/audioExample

# Spring??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_serve?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #?????
      initialSize: 5
      #???
      minIdle: 5
      #???
      maxActive: 20
      #??????????????????????????ms
      maxWait: 60000
      #?????????????????????????
      timeBetweenEvictionRunsMillis: 60000
      #????????????????
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      # ?????????filters????????sql?????
      #'wall'??????SpringBoot???log4j?????log4j2
      filters: stat,wall,log4j2
      #??PSCache??
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      # ??connectProperties?????mergeSql????SQL??
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # ??StatFilter
      web-stat-filter:
        #???false????true??
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #??StatViewServlet
      stat-view-servlet:
        url-pattern: "/druid/*"
        #????ip
        allow: 127.0.0.1
        login-username: admin
        login-password: 123456
        #????ip
        deny: 192.168.1.102
        #??????
        reset-enable: true
        #??
        enabled: true

# Mybatis??
mybatis:
  # ??XML???????????????
  type-aliases-package: com.fvauth.fvauthapp.domain
  # ??MyBatis?xml??????
  mapper-locations: classpath:mapper/*.xml
  # ????uName?????u_name
  map-underscore-to-camel-case: true

# ??sql
logging:
  level:
    ssm.app.mapper : debug









